project:
  name: "vietnamese_wordnet_embedding"
  language: "vi"
  seed: 42
  
hardware:
  device: "cuda"  
  fp16: True  
  gradient_accumulation: 2

monitoring:
  wandb_project: "vn_wordnet"
  log_interval: 100