project:
  name: "vietnamese_wordnet_embedding"
  language: "vi"
  seed: 42

base_model: "vinai/phobert-base"
base_model_cache_dir: "embeddings/vinai/phobert-base"
output_dir: "./checkpoints/phobert-base-bem"

data:
  train_path: "data/processed/polybert_exp/train_data.json"
  valid_path: "data/processed/polybert_exp/valid_data.json"
  num_workers: 16

training:
  ckpt_interval: 10
  shuffle: False
  batch_size: 128
  epochs: 100
  early_stopping_patience: 5
  save_steps: 1000
  optimizer:
    name: "adamw"
    lr: 2e-4 
    weight_decay: 0.01
    eps: 1e-6
    betas: [0.9, 0.999]
